# Generated by Django 3.1.2 on 2020-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201022_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='new', max_length=200),
            preserve_default=False,
        ),
    ]
