# Generated by Django 3.1.2 on 2020-10-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201024_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'Outwear'), ('SW', 'SportWear'), ('S', 'Shirt')], max_length=2),
        ),
    ]
